# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KDVPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='Preis in Cent')),
                ('quantity', models.PositiveIntegerField(verbose_name='Anzahl im Vorrat')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'pricings',
            },
        ),
        migrations.CreateModel(
            name='KDVProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Produktname')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'KDV-Produkte',
                'db_table': 'products',
                'verbose_name': 'KDV-Produkt',
            },
        ),
        migrations.CreateModel(
            name='KDVProductBarcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Barcode')),
                ('identifiable_type', models.CharField(default='Product', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('identifiable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kdvadmin.KDVProduct')),
            ],
            options={
                'db_table': 'kdv_product_identifiers',
            },
        ),
        migrations.AddField(
            model_name='kdvpricing',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kdvadmin.KDVProduct'),
        ),
    ]
