# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beitrag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titel')),
                ('author', models.CharField(max_length=250, verbose_name='Autor')),
                ('content_text', models.TextField(verbose_name='Inhalt')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Veröffentlichungsdatum')),
            ],
            options={
                'ordering': ['published_date'],
                'verbose_name': 'Beitrag',
                'verbose_name_plural': 'Beiträge',
            },
        ),
    ]
