# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oplan', '0007_auto_20160503_1638'),
        ('neuigkeiten', '0002_auto_20160503_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNewsSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_news', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('GCM', 'Google Cloud Messaging'), ('WEBPUSH', 'Open Web Push (Firefox)')], max_length=10)),
                ('token', models.CharField(max_length=255)),
                ('subscribed_aks', models.ManyToManyField(to='oplan.AK')),
            ],
        ),
    ]
