# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuigkeiten', '0003_pushnewssubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnewssubscriber',
            name='notification_body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pushnewssubscriber',
            name='notification_icon',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
