# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neuigkeiten', '0004_auto_20160503_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('icon', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='pushnewssubscriber',
            name='notification_body',
        ),
        migrations.RemoveField(
            model_name='pushnewssubscriber',
            name='notification_icon',
        ),
        migrations.AlterField(
            model_name='pushnewssubscriber',
            name='subscribed_aks',
            field=models.ManyToManyField(related_name='push_subscribers', to='oplan.AK'),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neuigkeiten.PushNewsSubscriber'),
        ),
    ]
