# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neuigkeiten', '0005_auto_20160503_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='identifier',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pushnotification',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='neuigkeiten.PushNewsSubscriber'),
        ),
    ]
