# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-02 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuigkeiten', '0006_auto_20160504_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pushnewssubscriber',
            old_name='token',
            new_name='push_uuid',
        ),
        migrations.AddField(
            model_name='pushnewssubscriber',
            name='subscription',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
