# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(blank=True, max_length=400, null=True, verbose_name='Bezeichnung')),
                ('leiter', models.CharField(blank=True, max_length=400, null=True, verbose_name="Wer macht's?")),
                ('anzahl', models.CharField(blank=True, max_length=400, null=True, verbose_name='Wie viele?')),
                ('wann', models.CharField(blank=True, max_length=400, null=True, verbose_name='Wann?')),
                ('dauer', models.CharField(blank=True, max_length=400, null=True, verbose_name='Dauer?')),
                ('beschreibung', models.TextField(blank=True, null=True)),
                ('wiki_link', models.CharField(blank=True, max_length=100, null=True, verbose_name='Link zur Wikiseite')),
            ],
            options={
                'verbose_name_plural': 'Arbeitskreise',
                'ordering': ('titel',),
                'verbose_name': 'Arbeitskreis',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Nummer')),
                ('type', models.CharField(choices=[('SR', 'Kleingruppenraum'), ('HS', 'Hörsaal'), ('PC', 'PC-Pool'), ('LZ', 'Lernzentrum'), ('SO', 'Sonstiges')], max_length=2, verbose_name='Typ')),
                ('has_beamer', models.BooleanField(default=False, verbose_name='Beamer vorhanden?')),
                ('capacity', models.IntegerField(verbose_name='Anzahl Plätze')),
                ('lat', models.FloatField(blank=True, default=0, verbose_name='Latitude')),
                ('lng', models.FloatField(blank=True, default=0, verbose_name='Longitude')),
                ('mgmt_source', models.CharField(blank=True, max_length=20)),
                ('mgmt_id', models.CharField(blank=True, max_length=50)),
                ('mgmt_link', models.CharField(blank=True, max_length=255)),
                ('mgmt_comment', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Räume',
                'ordering': ['number'],
                'verbose_name': 'Raum',
            },
        ),
        migrations.CreateModel(
            name='RoomOpening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Termin')),
                ('duration', models.DurationField(verbose_name='Dauer')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'OK (Reserved)'), (2, 'Blocked by other event'), (3, 'Should Request'), (4, 'Requested')])),
                ('kommentar', models.TextField(blank=True, verbose_name='Kommentar')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aks.Room', verbose_name='Raum')),
            ],
            options={
                'verbose_name_plural': 'Raumreservierungen',
                'verbose_name': 'Raumreservierung',
            },
        ),
        migrations.AddField(
            model_name='ak',
            name='assigned_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aks.RoomOpening', verbose_name='Zugewiesener Zeitslot'),
        ),
    ]
