# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(blank=True, max_length=400, verbose_name='Bezeichnung')),
                ('leiter', models.CharField(blank=True, max_length=400, verbose_name="Wer macht's?")),
                ('anzahl', models.CharField(blank=True, max_length=400, verbose_name='Wie viele?')),
                ('wann', models.CharField(blank=True, max_length=400, verbose_name='Wann?')),
                ('dauer', models.CharField(blank=True, max_length=400, verbose_name='Dauer?')),
            ],
            options={
                'ordering': ('titel',),
                'verbose_name': 'Arbeitskreis',
            },
        ),
    ]
