# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 01:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomopening',
            options={'verbose_name': 'AK-Slot'},
        ),
    ]
