# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiffel', '0003_auto_20160308_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kiffel',
            name='weitere_tshirts',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
