# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oplan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomavailability',
            name='mgmt_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aktermin',
            name='constraintAfterEvents',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nach Veranstaltung(en)'),
        ),
        migrations.AlterField(
            model_name='aktermin',
            name='constraintBeforeEvents',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vor Veranstaltung(en)'),
        ),
    ]
