# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nummer'),
        ),
    ]
