# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oplan', '0002_auto_20160421_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aktermin',
            options={'verbose_name': 'AK-Termin', 'verbose_name_plural': 'AK-Termine'},
        ),
        migrations.AlterModelOptions(
            name='roomavailability',
            options={'verbose_name': 'Raumverfügbarkeit oder Zeitslot', 'verbose_name_plural': 'Raumverfügbarkeiten und Zeitslots'},
        ),
        migrations.AddField(
            model_name='ak',
            name='color',
            field=models.CharField(default='#ff00ff', max_length=10, verbose_name='Farbe'),
        ),
        migrations.AlterField(
            model_name='aktermin',
            name='constraintAfterTime',
            field=models.DateTimeField(blank=True, max_length=255, null=True, verbose_name='Nicht vor Datum/Zeit'),
        ),
        migrations.AlterField(
            model_name='aktermin',
            name='constraintBeforeTime',
            field=models.DateTimeField(blank=True, max_length=255, null=True, verbose_name='Nicht nach Datum/Zeit'),
        ),
        migrations.AlterField(
            model_name='aktermin',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Scheduled'), (3, 'Not scheduled'), (4, 'Fixed (Do not autoschedule)')]),
        ),
        migrations.AlterField(
            model_name='room',
            name='mgmt_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID in Raumbuchungssystem'),
        ),
        migrations.AlterField(
            model_name='room',
            name='mgmt_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Link zum Raumbuchungssystem'),
        ),
        migrations.AlterField(
            model_name='room',
            name='mgmt_source',
            field=models.CharField(blank=True, max_length=20, verbose_name='Verwaltet durch Raumbuchungssystem'),
        ),
        migrations.AlterField(
            model_name='roomavailability',
            name='mgmt_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID in Raumbuchungssystem'),
        ),
    ]
