# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 10:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('oplan', '0003_auto_20160422_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktermin',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 22, 10, 25, 3, 330905, tzinfo=utc), verbose_name='Zuletzt geändert'),
            preserve_default=False,
        ),
    ]
