# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oplan', '0004_aktermin_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktermin',
            name='last_highlighted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Änderungshighlight'),
        ),
        migrations.AlterField(
            model_name='aktermin',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Zuletzt geändert'),
        ),
    ]
