# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oplan', '0005_auto_20160422_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='Im Frontend sichtbar'),
        ),
    ]
