# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oplan', '0006_room_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktermin',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Scheduled'), (3, 'Not scheduled'), (4, 'Fixed (Do not autoschedule)')], default=3),
        ),
    ]
