# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oplan', '0007_auto_20160503_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aktermin',
            name='constraintAfterEvents',
        ),
        migrations.AddField(
            model_name='aktermin',
            name='constraintAfterEvents',
            field=models.ManyToManyField(related_name='constraint_must_be_after_this', to='oplan.AKTermin', verbose_name='Nach Veranstaltung(en)'),
        ),
        migrations.RemoveField(
            model_name='aktermin',
            name='constraintBeforeEvents',
        ),
        migrations.AddField(
            model_name='aktermin',
            name='constraintBeforeEvents',
            field=models.ManyToManyField(related_name='constraint_must_be_before_this', to='oplan.AKTermin', verbose_name='Vor Veranstaltung(en)'),
        ),
        migrations.RemoveField(
            model_name='aktermin',
            name='constraintForceParallelWithEvents',
        ),
        migrations.AddField(
            model_name='aktermin',
            name='constraintForceParallelWithEvents',
            field=models.ManyToManyField(related_name='constraint_force_parallel_with_this', to='oplan.AKTermin', verbose_name='Gleichzeitig mit Veranstaltung(en)'),
        ),
        migrations.RemoveField(
            model_name='aktermin',
            name='constraintNotParallelWithEvents',
        ),
        migrations.AddField(
            model_name='aktermin',
            name='constraintNotParallelWithEvents',
            field=models.ManyToManyField(related_name='constraint_not_parallel_with_this', to='oplan.AKTermin', verbose_name='Nicht gleichzeitig mit Veranstaltung(en)'),
        ),
        migrations.RemoveField(
            model_name='aktermin',
            name='constraintRooms',
        ),
        migrations.AddField(
            model_name='aktermin',
            name='constraintRooms',
            field=models.ManyToManyField(blank=True, max_length=255, null=True, related_name='aktermin_constraint_room', to='oplan.Room', verbose_name='In einem der Räume'),
        ),
    ]
