# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 22:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oplan', '0009_auto_20160504_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='ak',
            name='interesse',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ak',
            name='leiter_personen',
            field=models.ManyToManyField(blank=True, help_text='Werden bei Zuteilung berücksichtigt', null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
