# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oplan', '0012_auto_20181026_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='ak',
            name='beamer',
            field=models.BooleanField(default=False, verbose_name='Beamer benötigt?'),
        ),
        migrations.AddField(
            model_name='ak',
            name='internet',
            field=models.BooleanField(default=False, verbose_name='Internet benötigt?'),
        ),
        migrations.AddField(
            model_name='ak',
            name='reso',
            field=models.BooleanField(default=False, verbose_name='Absicht auf eine Resolution?'),
        ),
        migrations.AddField(
            model_name='ak',
            name='whiteboard',
            field=models.BooleanField(default=False, verbose_name='Whiteboard oder Tafel benötigt?'),
        ),
    ]
