# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oplan', '0012_auto_20181026_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='color',
            field=models.CharField(default='#34495e', max_length=10, verbose_name='Farbe'),
        ),
    ]
