# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oplan', '0013_track_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ak',
            old_name='color',
            new_name='internal_color',
        ),
    ]
