# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oplan', '0015_auto_20181031_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ak_start_day', models.DateField(verbose_name='Erster AK-Tag')),
                ('ak_end_day', models.DateField(verbose_name='Letzer AK-Tag')),
                ('ak_start_hour', models.TimeField(verbose_name='Beginn der AKs (Uhrzeit)')),
                ('ak_end_hour', models.TimeField(verbose_name='Ende der AKs (Uhrzeit)')),
            ],
            options={
                'verbose_name': 'Einstellungen',
                'verbose_name_plural': 'Einstellungen',
            },
        ),
    ]
