# Generated by Django 2.2.2 on 2019-06-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oplan', '0016_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ak',
            name='beamer',
            field=models.BooleanField(default=False, help_text='Beamer benötigt?', verbose_name='Beamer?'),
        ),
        migrations.AlterField(
            model_name='ak',
            name='internet',
            field=models.BooleanField(default=False, help_text='Internet benötigt?', verbose_name='Internet?'),
        ),
        migrations.AlterField(
            model_name='ak',
            name='reso',
            field=models.BooleanField(default=False, help_text='Absicht auf eine Resolution?', verbose_name='Reso?'),
        ),
        migrations.AlterField(
            model_name='ak',
            name='whiteboard',
            field=models.BooleanField(default=False, help_text='Whiteboard oder Tafel benötigt?', verbose_name='WB?'),
        ),
    ]
