# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduroam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestaccount',
            name='login',
            field=models.CharField(max_length=100, unique=True, verbose_name='Accountname'),
        ),
    ]
