# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduroam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestaccount',
            name='nachname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guestaccount',
            name='perso_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Personalausweisnummer'),
        ),
        migrations.AlterField(
            model_name='guestaccount',
            name='vorname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
