# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduroam', '0002_auto_20160322_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestaccount',
            name='vergeben_am',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guestaccount',
            name='vergeben_durch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
