# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 23:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduroam', '0002_auto_20160424_0215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestaccount',
            options={'ordering': ('login',), 'permissions': (('assign_guestaccount', 'Assign existing guest accounts'),), 'verbose_name': 'Gastaccount'},
        ),
    ]
