# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kiffel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('nickname',),
            },
        ),
    ]
