# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kiffel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('vorname', models.CharField(max_length=100)),
                ('nachname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('student', models.BooleanField()),
                ('hochschule', models.CharField(max_length=100)),
                ('kommentar_public', models.TextField()),
                ('kommentar_orga', models.TextField()),
                ('anreise_geplant', models.DateTimeField()),
                ('abreise_geplant', models.DateTimeField()),
                ('ernaehrungsgewohnheit', models.CharField(max_length=100)),
                ('Lebensmittelunvertraeglichkeiten', models.CharField(max_length=400)),
                ('volljaehrig', models.BooleanField()),
                ('eigener_schlafplatz', models.BooleanField()),
                ('tshirt_groesse', models.CharField(max_length=10)),
                ('nickname_auf_tshirt', models.BooleanField()),
                ('kapuzenjacke', models.BooleanField()),
                ('nickname_auf_kapuzenjacke', models.BooleanField()),
                ('weitere_tshirts', models.IntegerField()),
                ('interesse_theater', models.BooleanField()),
                ('interesse_esoc', models.BooleanField()),
                ('anmeldung_angelegt', models.DateTimeField()),
                ('anmeldung_aktualisiert', models.DateTimeField()),
                ('datum_bezahlt', models.DateTimeField(null=True)),
                ('datum_tshirt_erhalten', models.DateTimeField(null=True)),
                ('datum_teilnahmebestaetigung_erhalten', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=100)),
                ('kommentar', models.TextField()),
                ('engel_handle', models.CharField(max_length=100)),
                ('twitter_handle', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('nickname',),
            },
        ),
    ]
