# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 00:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiffel', '0001_initial'),
    ]

    operations = [
        #migrations.CreateModel(
        #    name='KDVUserBarcode',
        #    fields=[
        #        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #        ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Barcode')),
        #        ('identifiable_type', models.CharField(default='User', max_length=255)),
        #        ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
        #        ('updated_at', models.DateTimeField(auto_now=True, null=True)),
        #    ],
        #    options={
        #        'db_table': 'kdv_user_identifiers',
        #    },
        #),
        migrations.RemoveField(
            model_name='person',
            name='kdv_id',
        ),
        migrations.AddField(
            model_name='person',
            name='kdv_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nickname'),
        ),
        #migrations.AddField(
        #    model_name='kdvuserbarcode',
        #    name='identifiable',
        #    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        #),
    ]
