# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiffel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='student',
            field=models.BooleanField(default=False),
        ),
    ]
