# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiffel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kiffel',
            old_name='Lebensmittelunvertraeglichkeiten',
            new_name='lebensmittelunvertraeglichkeiten',
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='datum_bezahlt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='datum_teilnahmebestaetigung_erhalten',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='datum_tshirt_erhalten',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
