# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 14:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiffel', '0002_auto_20160424_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='datum_tshirt_erhalten',
        ),
        migrations.AddField(
            model_name='person',
            name='datum_baendchen_erhalten',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bändchen erhalten'),
        ),
    ]
