# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiffel', '0002_auto_20160414_0000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('nickname',), 'permissions': (('import_persons', 'Personen importieren'),), 'verbose_name': 'Person', 'verbose_name_plural': 'Personen'},
        ),
        migrations.AlterField(
            model_name='person',
            name='datum_bezahlt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tn.beitrag bezahlt'),
        ),
        migrations.AlterField(
            model_name='person',
            name='kdv_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='KDV-ID'),
        ),
    ]
