# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiffel', '0002_auto_20160308_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kiffel',
            name='engel_handle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='ernaehrungsgewohnheit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='kommentar',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='kommentar_orga',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='kommentar_public',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='lebensmittelunvertraeglichkeiten',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
