# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiffel', '0004_auto_20160308_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kiffel',
            name='engel_handle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='ernaehrungsgewohnheit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='kommentar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='kommentar_orga',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='kommentar_public',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='lebensmittelunvertraeglichkeiten',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='weitere_tshirts',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
