# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiffel', '0005_auto_20160308_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kiffel',
            name='kapuzenjacke',
        ),
        migrations.AddField(
            model_name='kiffel',
            name='kapuzenjacke_groesse',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
