# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiffel', '0006_auto_20160308_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kiffel',
            options={'ordering': ('nickname',), 'verbose_name': 'Kiffel'},
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='datum_bezahlt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Teilnahmebeitrag bezahlt (Datum)'),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='datum_teilnahmebestaetigung_erhalten',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Teilnahmebestätigung erhalten (Datum)'),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='datum_tshirt_erhalten',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T-Shirt erhalten (Datum)'),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='eigener_schlafplatz',
            field=models.BooleanField(verbose_name='Hat eigenen Schlafplatz'),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='engel_handle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name im Engelsystem'),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='ernaehrungsgewohnheit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ernährungsgewohnheit'),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='hochschule',
            field=models.CharField(max_length=100, verbose_name='Hochschule/Ort/Verein'),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='interesse_esoc',
            field=models.BooleanField(verbose_name='Interesse an ESOC-Führung'),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='interesse_theater',
            field=models.BooleanField(verbose_name='Interesse an Theaterbesuch'),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='kapuzenjacke_groesse',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Kapuzenjacke (evtl. Größe)'),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='kommentar_orga',
            field=models.TextField(blank=True, null=True, verbose_name='Kommentar Orga'),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='kommentar_public',
            field=models.TextField(blank=True, null=True, verbose_name='Kommentar öffentlich'),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='lebensmittelunvertraeglichkeiten',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Lebensmittelunverträglichkeiten'),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='nickname',
            field=models.CharField(max_length=100, verbose_name='Nickname (Namensschild)'),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='nickname_auf_kapuzenjacke',
            field=models.BooleanField(verbose_name='Nickname auf Kapuzenjacke drucken'),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='nickname_auf_tshirt',
            field=models.BooleanField(verbose_name='Nickname auf T-Shirt drucken'),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='tshirt_groesse',
            field=models.CharField(max_length=10, verbose_name='T-Shirt-Größe'),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Twitter-Handle'),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='volljaehrig',
            field=models.BooleanField(verbose_name='Volljährig (über 18)'),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='weitere_tshirts',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Weitere T-Shirts'),
        ),
    ]
