# Generated by Django 2.2.2 on 2019-06-24 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiffel', '0006_auto_20181030_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kdvuserbarcode',
            options={'managed': True},
        ),
    ]
