# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiffel', '0007_auto_20160309_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiffel',
            name='kdv_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='KDV-ID (Barcode-Nummer)'),
        ),
    ]
