# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiffel', '0009_kiffel_ist_orga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kiffel',
            name='datum_bezahlt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Teilnahmebeitrag bezahlt'),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='datum_teilnahmebestaetigung_erhalten',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Teilnahmebestätigung erhalten'),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='datum_tshirt_erhalten',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T-Shirt erhalten'),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='ist_orga',
            field=models.BooleanField(default=False, verbose_name='Kiffel ist Orga'),
        ),
        migrations.AlterField(
            model_name='kiffel',
            name='kdv_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='KDV-ID'),
        ),
    ]
